### ISSUE TITLE
KoleCZko 2018 TODO

### ISSUE THREAD

**Issue by KoleckoOrg** [mfrodl/kolecko#20]
The archiving of KoleCZko 2018 is mostly done with just a few small tasks left:

- [ ]  Reread/polish the language in puzzles
- [ ]  Find somewhere the 10th puzzle with logo
- [ ]  Show the team names to registered users only
- [ ]  Styling
- [ ]  Look harder for photos
- [ ]  Moreover I would prefer to only have "Minulé ročníky": KoleCZko 2018 link in the main menu, which would link to a page  /archiv/2018 with some brief introduction and a full menu of all the 2018 subpages (without the menu items from current year and only single link to "Aktuální ročník"). The main motivation is to separate more the current and last years and simplify the menu.
